config:
  freellmapi-infrastructure:image: anicu/freellmapi:2026.05.05-10531d0-6
  freellmapi-infrastructure:namespace: freellmapi-dev
  freellmapi-infrastructure:host: freellmapi-dev.167-235-219-49.sslip.io
  freellmapi-infrastructure:kubeconfigContext: kubernetes-admin@kubernetes
  freellmapi-infrastructure:allowlist: 81.96.238.148/32,17.243.140.51/32,31.94.72.164/32,2a01:b740:13d0::b5/128,2a00:23ee:2828:4849:dcf2:493e:b7a6:e78b/128
  freellmapi-infrastructure:storageSize: 1Gi
  # Set after first `pulumi stack init`:
  #   pulumi config set --secret encryptionKey <64-char hex from `openssl rand -hex 32`>

  freellmapi-infrastructure:encryptionKey:
    secure: AAABAJeis24YVZeekg6t34FTi9Z3NYIiXE3FHuxlMhbnC5lJ5RtPDyaIQVpwz2WZQbtAsqBK0OPOvgaMMiwO8MnjY9h33TAZBe1rFau57eRIC9KzTMK7AB9s+VwZy9mU
